# Generated by Django 5.2.12 on 2026-06-06 21:58

import apps.accounts.models
import apps.common.validators
import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_update_admin_role_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Imagem quadrada recomendada. É convertida e otimizada automaticamente.', upload_to=apps.accounts.models.avatar_upload_path, validators=[apps.common.validators.validate_uploaded_image], verbose_name='Foto de perfil'),
        ),
    ]
