# Generated by Django 5.2.16 on 2026-07-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Administrador'), ('school_admin', 'Administrador Komuniki'), ('news_editor', 'Editor de Notícias'), ('reporter', 'Repórter'), ('hiring_manager', 'Contratações (guardado)')], default='news_editor', help_text='Define as permissões e acesso do usuário no sistema.', max_length=20, verbose_name='Cargo'),
        ),
    ]
