# Generated by Django 5.2.11 on 2026-06-02 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_newsletter_sent_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviado'), ('failed', 'Falhou'), ('skipped', 'Ignorado')], default='pending', max_length=20, verbose_name='Status')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Tentativas')),
                ('last_error', models.TextField(blank=True, verbose_name='Último erro')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado em')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletter_deliveries', to='news.article', verbose_name='Artigo')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='news.newslettersubscription', verbose_name='Assinatura')),
            ],
            options={
                'verbose_name': 'Entrega de Newsletter',
                'verbose_name_plural': 'Entregas de Newsletter',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='news_newsle_status_30462d_idx'), models.Index(fields=['article', 'status'], name='news_newsle_article_21d80e_idx')],
                'unique_together': {('article', 'subscription')},
            },
        ),
    ]
