# Generated by Django 5.2.12 on 2026-06-10 03:12

import apps.common.validators
import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_newsletterdelivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='featured_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Imagem principal que aparece no topo do artigo. É convertida e otimizada automaticamente.', upload_to='news/articles/', validators=[apps.common.validators.validate_uploaded_image], verbose_name='Imagem de capa'),
        ),
    ]
