# Generated by Django 5.2.12 on 2026-06-10 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0002_pt_br_admin_labels'),
        ('news', '0012_alter_article_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, editable=False, help_text='Texto consolidado dos blocos de conteúdo (gerado automaticamente).', verbose_name='Conteúdo'),
        ),
        migrations.CreateModel(
            name='ArticleBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Ordem')),
                ('block_type', models.CharField(choices=[('rich_text', 'Texto'), ('image', 'Imagem'), ('embed', 'Vídeo / Post')], default='rich_text', max_length=20, verbose_name='Tipo de bloco')),
                ('rich_text', models.TextField(blank=True, help_text='Parágrafos, subtítulos, listas e links do artigo.', verbose_name='Texto')),
                ('caption', models.CharField(blank=True, help_text='Texto opcional exibido abaixo da imagem ou do vídeo/post.', max_length=255, verbose_name='Legenda')),
                ('embed_url', models.URLField(blank=True, help_text='Cole o link do YouTube, Instagram ou TikTok. O embed é gerado automaticamente.', verbose_name='Link do vídeo/post')),
                ('embed_provider', models.CharField(blank=True, editable=False, max_length=20, verbose_name='Plataforma')),
                ('embed_id', models.CharField(blank=True, editable=False, max_length=255, verbose_name='ID do embed')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='news.article', verbose_name='Artigo')),
                ('media', models.ForeignKey(blank=True, help_text='Selecione na Biblioteca de Mídia ou envie uma nova (otimizada automaticamente).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_blocks', to='media_library.mediafile', verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Bloco de conteúdo',
                'verbose_name_plural': 'Blocos de conteúdo',
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['article', 'order'], name='news_articl_article_b65f23_idx')],
            },
        ),
    ]
