# Generated by Django 5.2.16 on 2026-07-23 23:30

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_content_to_blocks'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='body',
            field=wagtail.fields.StreamField([('titulo', 2), ('texto', 3), ('citacao', 6), ('separador', 7), ('imagem', 10), ('embed', 12), ('documento', 13), ('destaque', 16), ('tabela', 17), ('fonte', 20)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Texto', 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'Título'), ('h3', 'Subtítulo'), ('h4', 'Subtítulo menor')], 'label': 'Nível'}), 2: ('wagtail.blocks.StructBlock', [[('texto', 0), ('nivel', 1)]], {'group': 'Texto'}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'underline', 'strikethrough', 'ol', 'ul', 'link', 'document-link', 'blockquote', 'code', 'superscript', 'subscript', 'hr'], 'group': 'Texto', 'icon': 'pilcrow', 'label': 'Texto rico'}), 4: ('wagtail.blocks.TextBlock', (), {'label': 'Citação', 'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Atribuição', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('citacao', 4), ('atribuicao', 5)]], {'group': 'Texto'}), 7: ('apps.news.blocks.SeparatorBlock', (), {'group': 'Texto'}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagem', 'required': True}), 9: ('wagtail.blocks.CharBlock', (), {'label': 'Legenda', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('imagem', 8), ('legenda', 9)]], {'group': 'Mídia'}), 11: ('wagtail.blocks.URLBlock', (), {'help_text': 'Cole o link do YouTube, Instagram ou TikTok.', 'label': 'Link do vídeo/post', 'required': True}), 12: ('wagtail.blocks.StructBlock', [[('embed_url', 11)]], {'group': 'Mídia'}), 13: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'group': 'Mídia'}), 14: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Informativo'), ('alerta', 'Alerta'), ('destaque', 'Destaque')], 'label': 'Estilo'}), 15: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'label': 'Texto'}), 16: ('wagtail.blocks.StructBlock', [[('estilo', 14), ('texto', 15)]], {'group': 'Destaques'}), 17: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'group': 'Dados'}), 18: ('wagtail.blocks.CharBlock', (), {'label': 'Rótulo', 'required': True}), 19: ('wagtail.blocks.URLBlock', (), {'label': 'Link', 'required': True}), 20: ('wagtail.blocks.StructBlock', [[('rotulo', 18), ('url', 19)]], {'group': 'Dados'})}, null=True, verbose_name='Conteúdo (blocos)'),
        ),
        migrations.AddField(
            model_name='article',
            name='expire_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='expiry date/time'),
        ),
        migrations.AddField(
            model_name='article',
            name='expired',
            field=models.BooleanField(default=False, editable=False, verbose_name='expired'),
        ),
        migrations.AddField(
            model_name='article',
            name='first_published_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='first published at'),
        ),
        migrations.AddField(
            model_name='article',
            name='go_live_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='go live date/time'),
        ),
        migrations.AddField(
            model_name='article',
            name='has_unpublished_changes',
            field=models.BooleanField(default=False, editable=False, verbose_name='has unpublished changes'),
        ),
        migrations.AddField(
            model_name='article',
            name='last_published_at',
            field=models.DateTimeField(editable=False, null=True, verbose_name='last published at'),
        ),
        migrations.AddField(
            model_name='article',
            name='latest_revision',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='latest revision'),
        ),
        migrations.AddField(
            model_name='article',
            name='live',
            field=models.BooleanField(default=True, editable=False, verbose_name='live'),
        ),
        migrations.AddField(
            model_name='article',
            name='live_revision',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='live revision'),
        ),
        migrations.AddField(
            model_name='article',
            name='locked',
            field=models.BooleanField(default=False, editable=False, verbose_name='locked'),
        ),
        migrations.AddField(
            model_name='article',
            name='locked_at',
            field=models.DateTimeField(editable=False, null=True, verbose_name='locked at'),
        ),
        migrations.AddField(
            model_name='article',
            name='locked_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='locked by'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Digite para buscar tags existentes.', related_name='articles', to='news.tag', verbose_name='Tags'),
        ),
    ]
