# Generated by Django 5.2.12 on 2026-07-15 23:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_content_to_blocks'),
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['site', 'status', '-published_at'], name='news_art_site_status_pub'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status', 'newsletter_sent_at'], name='news_art_status_newsletter'),
        ),
    ]
