# Generated by Django 5.2.16 on 2026-07-24 00:12

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_article_body_article_expire_at_article_expired_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=wagtail.fields.StreamField([('titulo', 2), ('texto', 3), ('citacao', 6), ('separador', 7), ('imagem', 10), ('embed', 13), ('documento', 14), ('destaque', 17), ('tabela', 18), ('fonte', 21)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Texto', 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'Título'), ('h3', 'Subtítulo'), ('h4', 'Subtítulo menor')], 'label': 'Nível'}), 2: ('wagtail.blocks.StructBlock', [[('texto', 0), ('nivel', 1)]], {'group': 'Texto'}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'underline', 'strikethrough', 'ol', 'ul', 'link', 'document-link', 'blockquote', 'code', 'superscript', 'subscript', 'hr'], 'group': 'Texto', 'icon': 'pilcrow', 'label': 'Texto rico'}), 4: ('wagtail.blocks.TextBlock', (), {'label': 'Citação', 'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Atribuição', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('citacao', 4), ('atribuicao', 5)]], {'group': 'Texto'}), 7: ('apps.news.blocks.SeparatorBlock', (), {'group': 'Texto'}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Imagem', 'required': True}), 9: ('wagtail.blocks.CharBlock', (), {'label': 'Legenda', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('imagem', 8), ('legenda', 9)]], {'group': 'Mídia'}), 11: ('wagtail.blocks.URLBlock', (), {'help_text': 'Cole o link do YouTube, Instagram ou TikTok.', 'label': 'Link do vídeo/post', 'required': True}), 12: ('wagtail.blocks.CharBlock', (), {'help_text': 'Texto opcional exibido abaixo do vídeo/post.', 'label': 'Legenda', 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('embed_url', 11), ('legenda', 12)]], {'group': 'Mídia'}), 14: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'group': 'Mídia'}), 15: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Informativo'), ('alerta', 'Alerta'), ('destaque', 'Destaque')], 'label': 'Estilo'}), 16: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'label': 'Texto'}), 17: ('wagtail.blocks.StructBlock', [[('estilo', 15), ('texto', 16)]], {'group': 'Destaques'}), 18: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'group': 'Dados'}), 19: ('wagtail.blocks.CharBlock', (), {'label': 'Rótulo', 'required': True}), 20: ('wagtail.blocks.URLBlock', (), {'label': 'Link', 'required': True}), 21: ('wagtail.blocks.StructBlock', [[('rotulo', 19), ('url', 20)]], {'group': 'Dados'})}, null=True, verbose_name='Conteúdo (blocos)'),
        ),
    ]
