# Generated by Django 5.2.16 on 2026-07-24 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_media', '0001_initial'),
        ('news', '0017_setup_default_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='featured_image_wagtail',
            field=models.ForeignKey(blank=True, help_text='Nova imagem de capa pelo sistema Wagtail. Use este campo em vez do campo acima para novos artigos — o antigo continua funcionando, mas não aparece mais no painel Wagtail.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cms_media.image', verbose_name='Imagem de capa (Wagtail)'),
        ),
    ]
