# Generated by Django 5.2.16 on 2026-07-24 04:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_media', '0001_initial'),
        ('news', '0019_backfill_content_from_body'),
        ('sites', '0002_alter_domain_unique'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, editable=False, help_text='Texto consolidado gerado automaticamente a partir do corpo (body) do artigo.', verbose_name='Conteúdo'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(help_text='Gerado automaticamente a partir do título.', max_length=200, verbose_name='URL amigável'),
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.UniqueConstraint(fields=('site', 'slug'), name='unique_article_slug_per_site'),
        ),
    ]
