# Generated by Django 5.2.16 on 2026-07-24 05:47

import apps.news.models
import django.contrib.sites.managers
import django.db.models.deletion
import django.db.models.manager
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0021_delete_articleblock'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsHomeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, help_text='Título para buscadores (Google). Recomendado: até 70 caracteres.', max_length=70, verbose_name='Título SEO')),
                ('meta_description', models.CharField(blank=True, help_text='Descrição para buscadores (Google). Recomendado: até 160 caracteres.', max_length=160, verbose_name='Descrição SEO')),
                ('meta_keywords', models.CharField(blank=True, help_text='Palavras-chave separadas por vírgula. Ex: educação, escola, notícias.', max_length=255, verbose_name='Palavras-chave SEO')),
                ('is_active', models.BooleanField(default=True, help_text='Desligado: a home volta ao comportamento automático.', verbose_name='Ativo')),
                ('secondary_highlights', wagtail.fields.StreamField([('artigo', 0)], blank=True, block_lookup={0: ('wagtail.snippets.blocks.SnippetChooserBlock', (apps.news.models.Article,), {'label': 'Artigo'})}, help_text='2 a 4 artigos publicados, na ordem desejada. Vazio: a seção não aparece.', verbose_name='Destaques secundários')),
                ('hero_override', models.ForeignKey(blank=True, help_text='Substitui o destaque automático. Deixe vazio para manter o comportamento atual.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='news.article', verbose_name='Destaque manual do hero')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='news_home_config', to='sites.site')),
            ],
            options={
                'verbose_name': 'Configuração da Home de Notícias',
                'verbose_name_plural': 'Configurações da Home de Notícias',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
    ]
