# Generated by Django 5.2.16 on 2026-09-24 16:08

import apps.common.validators
import apps.news.models
import django.db.models.deletion
import imagekit.models.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_media', '0002_alter_document_options_alter_image_options'),
        ('news', '0028_timestamp_labels'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_at'], 'verbose_name': 'Notícia', 'verbose_name_plural': 'Notícias'},
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(help_text='Escolha a categoria principal da notícia.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='news.category', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, editable=False, help_text='Texto consolidado gerado automaticamente a partir do corpo (body) da notícia.', verbose_name='Conteúdo'),
        ),
        migrations.AlterField(
            model_name='article',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Resumo curto da notícia. Aparece nas listagens e compartilhamentos.', verbose_name='Resumo'),
        ),
        migrations.AlterField(
            model_name='article',
            name='featured_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Imagem principal que aparece no topo da notícia. É convertida e otimizada automaticamente.', upload_to='news/articles/', validators=[apps.common.validators.validate_uploaded_image], verbose_name='Imagem de capa'),
        ),
        migrations.AlterField(
            model_name='article',
            name='featured_image_wagtail',
            field=models.ForeignKey(blank=True, help_text='Nova imagem de capa pelo sistema Wagtail. Use este campo em vez do campo acima para novas notícias — o antigo continua funcionando, mas não aparece mais no painel Wagtail.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cms_media.image', verbose_name='Imagem de capa (Wagtail)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Notícias destacadas aparecem em posição de destaque na página principal.', verbose_name='Destaque'),
        ),
        migrations.AlterField(
            model_name='article',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Título para buscadores (Google). Se vazio, usa o título da notícia.', max_length=70, verbose_name='Título SEO'),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='Data e hora da publicação. Preenchido automaticamente ao publicar.', null=True, verbose_name='Publicada em'),
        ),
        migrations.AlterField(
            model_name='article',
            name='site',
            field=models.ForeignKey(help_text='Em qual portal esta notícia será publicada.', on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='sites.site', verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicada'), ('archived', 'Arquivada')], default='draft', help_text='Rascunho: não publicada. Publicada: visível no site. Arquivada: removida do site.', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='articlebookmark',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='news.article', verbose_name='Notícia'),
        ),
        migrations.AlterField(
            model_name='articlelike',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='news.article', verbose_name='Notícia'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.article', verbose_name='Notícia'),
        ),
        migrations.AlterField(
            model_name='newshomeconfig',
            name='secondary_highlights',
            field=wagtail.fields.StreamField([('artigo', 0)], blank=True, block_lookup={0: ('wagtail.snippets.blocks.SnippetChooserBlock', (apps.news.models.Article,), {'label': 'Notícia'})}, help_text='2 a 4 notícias publicadas, na ordem desejada. Vazio: a seção não aparece.', verbose_name='Destaques secundários'),
        ),
        migrations.AlterField(
            model_name='newsletterdelivery',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletter_deliveries', to='news.article', verbose_name='Notícia'),
        ),
    ]
