# Generated by Django 5.2.12 on 2026-06-02 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_contactinquiry_options_and_more'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinquiry',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='message',
            field=models.TextField(verbose_name='Mensagem'),
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='sites.site', verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='status',
            field=models.CharField(choices=[('new', 'Nova'), ('read', 'Lida'), ('replied', 'Respondida'), ('archived', 'Arquivada')], default='new', help_text='Marque como Lida, Respondida ou Arquivada conforme o atendimento.', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='subject',
            field=models.CharField(choices=[('general', 'Geral'), ('admissions', 'Admissões'), ('support', 'Suporte'), ('other', 'Outro')], default='general', max_length=50, verbose_name='Assunto'),
        ),
    ]
