# Generated by Django 5.2.16 on 2026-09-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_pt_br_admin_field_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinquiry',
            name='course_interest',
            field=models.CharField(blank=True, help_text='Preenchido quando o visitante chega pelo card de um curso na página Cursos.', max_length=120, verbose_name='Curso de interesse'),
        ),
    ]
