# Generated by Django 5.2.16 on 2026-07-24 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_media', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'permissions': [('choose_document', 'Can choose document')], 'verbose_name': 'Documento', 'verbose_name_plural': 'Documentos'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'permissions': [('choose_image', 'Can choose image')], 'verbose_name': 'Imagem', 'verbose_name_plural': 'Imagens'},
        ),
    ]
