# Generated by Django 5.2.12 on 2026-05-29 00:48

import apps.hiring.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0004_alter_jobposting_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(upload_to=apps.hiring.models.resume_upload_path),
        ),
    ]
