# Generated by Codex on 2026-06-01

import django.contrib.sites.managers
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


def assign_default_site(apps, schema_editor):
    Site = apps.get_model('sites', 'Site')
    Department = apps.get_model('hiring', 'Department')
    JobPosting = apps.get_model('hiring', 'JobPosting')

    default_site = Site.objects.order_by('pk').first()
    if default_site is None:
        default_site = Site.objects.create(domain='example.com', name='Default')

    Department.objects.filter(site__isnull=True).update(site=default_site)
    JobPosting.objects.filter(site__isnull=True).update(site=default_site)


def noop_reverse(apps, schema_editor):
    # Mantem dados atribuidos ao site para reversoes parciais seguras.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0005_alter_application_resume'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
        migrations.AddField(
            model_name='department',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='sites.site'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='sites.site'),
        ),
        migrations.RunPython(assign_default_site, noop_reverse),
        migrations.AlterField(
            model_name='department',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='sites.site'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='sites.site'),
        ),
        migrations.AlterModelManagers(
            name='department',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='jobposting',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('site', 'slug'), name='unique_department_slug_per_site'),
        ),
        migrations.AddConstraint(
            model_name='jobposting',
            constraint=models.UniqueConstraint(fields=('site', 'slug'), name='unique_job_posting_slug_per_site'),
        ),
    ]
