# Generated by Django 5.2.12 on 2026-06-02 20:16

import apps.hiring.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0006_site_isolation'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cover_letter',
            field=models.TextField(blank=True, verbose_name='Carta de apresentação'),
        ),
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='application',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='application',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='hiring.jobposting', verbose_name='Vaga'),
        ),
        migrations.AlterField(
            model_name='application',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Sobrenome'),
        ),
        migrations.AlterField(
            model_name='application',
            name='notes',
            field=models.TextField(blank=True, help_text='Notas internas sobre o candidato. Não visíveis ao candidato.', verbose_name='Notas internas'),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(upload_to=apps.hiring.models.resume_upload_path, verbose_name='Currículo'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('received', 'Recebida'), ('reviewing', 'Em Análise'), ('shortlisted', 'Pré-selecionada'), ('interview', 'Entrevista'), ('rejected', 'Rejeitada'), ('accepted', 'Aceita')], default='received', help_text='Acompanhe o progresso desta candidatura.', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='department',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='sites.site', verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='department',
            name='slug',
            field=models.SlugField(max_length=200, verbose_name='URL amigável'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='deadline',
            field=models.DateTimeField(blank=True, help_text='Data limite para receber candidaturas.', null=True, verbose_name='Prazo final'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='hiring.department', verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='description',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'Tempo Integral'), ('part_time', 'Meio Período'), ('contract', 'Contrato'), ('internship', 'Estágio')], default='full_time', max_length=20, verbose_name='Tipo de contratação'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Local'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Publicado em'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='requirements',
            field=models.TextField(verbose_name='Requisitos'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='salary_range',
            field=models.CharField(blank=True, max_length=200, verbose_name='Faixa salarial'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='sites.site', verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='slug',
            field=models.SlugField(max_length=200, verbose_name='URL amigável'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('open', 'Aberta'), ('closed', 'Fechada')], default='draft', help_text='Rascunho: não visível. Aberta: visível no site. Fechada: removida do site.', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
    ]
