# Generated by Django 5.2.16 on 2026-09-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0007_pt_br_admin_field_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('open', 'Aberta'), ('closed', 'Fechada')], default='draft', help_text='Situação interna da vaga. As vagas não são publicadas no site.', max_length=20, verbose_name='Status'),
        ),
    ]
