# Generated by Django 5.2.11 on 2026-02-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_siteextension_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteextension',
            name='newsletter_from_email',
            field=models.EmailField(blank=True, help_text='E-mail que aparecerá como remetente das newsletters. Ex: noticias@seusite.com', max_length=254, verbose_name='E-mail remetente da Newsletter'),
        ),
        migrations.AddField(
            model_name='siteextension',
            name='newsletter_from_name',
            field=models.CharField(blank=True, help_text='Nome exibido como remetente. Ex: Equipe News Portal', max_length=100, verbose_name='Nome remetente da Newsletter'),
        ),
    ]
