# Generated by Django 5.2.12 on 2026-06-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_siteextension_for_all_sites'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteextension',
            name='social_section_enabled',
            field=models.BooleanField(default=True, help_text='Quando ativo, a home mostra a seção de redes sociais (botões e posts recentes).', verbose_name='Exibir seção de redes na home'),
        ),
        migrations.AddField(
            model_name='siteextension',
            name='social_section_subtitle',
            field=models.CharField(default='Veja bastidores, conteúdos, eventos e novidades publicados no Instagram e TikTok.', max_length=255, verbose_name='Subtítulo da seção de redes'),
        ),
        migrations.AddField(
            model_name='siteextension',
            name='social_section_subtitle_en',
            field=models.CharField(blank=True, default='See behind the scenes, content, events and news posted on Instagram and TikTok.', help_text='Opcional. Se vazio, usa o subtítulo em português.', max_length=255, verbose_name='Subtítulo da seção de redes (EN)'),
        ),
        migrations.AddField(
            model_name='siteextension',
            name='social_section_title',
            field=models.CharField(default='Acompanhe a Komuniki nas redes', max_length=120, verbose_name='Título da seção de redes'),
        ),
        migrations.AddField(
            model_name='siteextension',
            name='social_section_title_en',
            field=models.CharField(blank=True, default='Follow Komuniki on social media', help_text='Opcional. Se vazio, usa o título em português.', max_length=120, verbose_name='Título da seção de redes (EN)'),
        ),
        migrations.AddField(
            model_name='siteextension',
            name='tiktok_url',
            field=models.URLField(blank=True, verbose_name='TikTok'),
        ),
    ]
