# Generated by Django 5.2.12 on 2026-06-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_siteextension_social_section_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteextension',
            name='social_show_instagram',
            field=models.BooleanField(default=True, help_text='Mostra o botão e os posts do Instagram na seção da home.', verbose_name='Exibir Instagram na seção'),
        ),
        migrations.AddField(
            model_name='siteextension',
            name='social_show_tiktok',
            field=models.BooleanField(default=True, help_text='Mostra os posts do TikTok na seção da home.', verbose_name='Exibir TikTok na seção'),
        ),
    ]
