# Generated by Codex on 2026-06-01

import django.contrib.sites.managers
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


def assign_default_site(apps, schema_editor):
    Site = apps.get_model('sites', 'Site')
    TeamMember = apps.get_model('school', 'TeamMember')
    Testimonial = apps.get_model('school', 'Testimonial')

    default_site = Site.objects.order_by('pk').first()
    if default_site is None:
        default_site = Site.objects.create(domain='example.com', name='Default')

    TeamMember.objects.filter(site__isnull=True).update(site=default_site)
    Testimonial.objects.filter(site__isnull=True).update(site=default_site)


def noop_reverse(apps, schema_editor):
    # Mantem dados atribuidos ao site para reversoes parciais seguras.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_page_managers'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolHomeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, help_text='Título para buscadores (Google). Recomendado: até 70 caracteres.', max_length=70, verbose_name='Título SEO')),
                ('meta_description', models.CharField(blank=True, help_text='Descrição para buscadores (Google). Recomendado: até 160 caracteres.', max_length=160, verbose_name='Descrição SEO')),
                ('meta_keywords', models.CharField(blank=True, help_text='Palavras-chave separadas por vírgula. Ex: educação, escola, notícias.', max_length=255, verbose_name='Palavras-chave SEO')),
                ('hero_badge', models.CharField(default='Educação com propósito', max_length=120, verbose_name='Selo do hero')),
                ('hero_title', models.CharField(default='Educação que prepara para o futuro', max_length=200, verbose_name='Título do hero')),
                ('hero_subtitle', models.TextField(default='Um ambiente de aprendizagem que une cuidado, conhecimento e desenvolvimento humano para acompanhar cada estudante de perto.', verbose_name='Subtítulo do hero')),
                ('visual_eyebrow', models.CharField(default='Comunidade escolar', max_length=120, verbose_name='Chamada visual')),
                ('visual_title', models.CharField(default='Aprender com presença, escuta e projeto.', max_length=200, verbose_name='Título do bloco visual')),
                ('visual_footer_title', models.CharField(default='Famílias, estudantes e educadores no mesmo projeto', max_length=200, verbose_name='Título do bloco de comunidade')),
                ('visual_footer_text', models.TextField(default='Comunicação clara para que a comunidade acompanhe a vida escolar com confiança.', verbose_name='Texto do bloco de comunidade')),
                ('proposal_eyebrow', models.CharField(default='Proposta pedagógica', max_length=120, verbose_name='Chamada da proposta')),
                ('proposal_title', models.CharField(default='Por que escolher nossa escola?', max_length=200, verbose_name='Título da proposta')),
                ('proposal_description', models.TextField(default='Uma experiência escolar consistente nasce do equilíbrio entre método, vínculo humano, segurança e projetos que ampliam repertórios.', verbose_name='Descrição da proposta')),
                ('life_eyebrow', models.CharField(default='Vida escolar', max_length=120, verbose_name='Chamada de vida escolar')),
                ('life_title', models.CharField(default='Uma escola com presença, projetos e comunidade', max_length=200, verbose_name='Título de vida escolar')),
                ('life_description', models.TextField(default='O cotidiano escolar ganha força quando aprendizagem, cultura, movimento e convivência se encontram em experiências reais.', verbose_name='Descrição de vida escolar')),
                ('team_eyebrow', models.CharField(default='Nossa equipe', max_length=120, verbose_name='Chamada da equipe')),
                ('team_title', models.CharField(default='Pessoas que constroem a experiência escolar', max_length=200, verbose_name='Título da equipe')),
                ('team_description', models.TextField(default='Educadores e profissionais que acompanham a rotina da escola com cuidado, organização e compromisso formativo.', verbose_name='Descrição da equipe')),
                ('testimonials_eyebrow', models.CharField(default='Depoimentos', max_length=120, verbose_name='Chamada de depoimentos')),
                ('testimonials_title', models.CharField(default='Vozes da comunidade', max_length=200, verbose_name='Título de depoimentos')),
                ('testimonials_description', models.TextField(default='Relatos ajudam a mostrar a relação de confiança construída no cotidiano escolar.', verbose_name='Descrição de depoimentos')),
                ('hiring_title', models.CharField(default='Faça parte da nossa equipe', max_length=200, verbose_name='Título de trabalhe conosco')),
                ('hiring_description', models.TextField(default='Profissionais da educação encontram aqui um espaço para conhecer oportunidades e participar de uma comunidade comprometida com formação humana.', verbose_name='Descrição de trabalhe conosco')),
                ('contact_title', models.CharField(default='Vamos conversar?', max_length=200, verbose_name='Título de contato')),
                ('contact_description', models.TextField(default='Pais, responsáveis e comunidade podem entrar em contato para tirar dúvidas, enviar mensagens ou iniciar uma conversa com a escola.', verbose_name='Descrição de contato')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='school_home_config', to='sites.site')),
            ],
            options={
                'verbose_name': 'Configuração da Home Escolar',
                'verbose_name_plural': 'Configurações da Home Escolar',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.CreateModel(
            name='SchoolFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('placement', models.CharField(choices=[('trust', 'Barra de confiança'), ('proposal', 'Proposta pedagógica'), ('life', 'Vida escolar')], max_length=20, verbose_name='Local de exibição')),
                ('title', models.CharField(max_length=160, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('tone', models.CharField(choices=[('emerald', 'Verde institucional'), ('amber', 'Âmbar'), ('slate', 'Slate'), ('white', 'Branco')], default='emerald', max_length=20, verbose_name='Tom visual')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_features', to='sites.site')),
            ],
            options={
                'verbose_name': 'Diferencial da Escola',
                'verbose_name_plural': 'Diferenciais da Escola',
                'ordering': ['placement', 'order', 'title'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
        migrations.AddField(
            model_name='teammember',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='sites.site'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='sites.site'),
        ),
        migrations.RunPython(assign_default_site, noop_reverse),
        migrations.AlterField(
            model_name='teammember',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='sites.site'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='sites.site'),
        ),
        migrations.AlterModelManagers(
            name='teammember',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='testimonial',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='page',
            constraint=models.UniqueConstraint(fields=('site', 'slug'), name='unique_school_page_slug_per_site'),
        ),
        migrations.AddConstraint(
            model_name='schoolfeature',
            constraint=models.UniqueConstraint(fields=('site', 'placement', 'title'), name='unique_school_feature_title_per_site_placement'),
        ),
    ]
