# Generated by Django 5.2.12 on 2026-06-05 19:48

from django.db import migrations, models


HOME_CONTENT_PT = {
    'hero_badge': 'Escola de comunicação, artes e liderança',
    'hero_title': 'Comunicação que gera resultados',
    'hero_subtitle': 'Mentorias e cursos para quem quer se expressar melhor, atuar nos meios audiovisuais, empreender na arte e construir presença com clareza.',
    'visual_eyebrow': 'Komuniki',
    'visual_title': 'Educação para comunicação e artes',
    'visual_footer_title': 'Cursos, mentorias e projetos com aplicação real',
    'visual_footer_text': 'A Komuniki une formação técnica, prática de mercado e acompanhamento próximo para pessoas, artistas, comunicadores e equipes corporativas.',
    'proposal_eyebrow': 'O que fazemos',
    'proposal_title': 'Cursos para comunicação, cultura e presença profissional',
    'proposal_description': 'Criada por Kelly Farias, a Komuniki oferece formações profissionalizantes, cursos livres e mentorias para comunicação, cultura, palco, escrita e autoconfiança.',
    'life_eyebrow': 'Projetos e impacto',
    'life_title': 'Comunicação, cultura e protagonismo',
    'life_description': 'A Komuniki também realiza o projeto social Jovem Comunicador, voltado a jovens em situação de vulnerabilidade social, e promove conexões entre formação, arte e mercado.',
    'team_eyebrow': 'Mentorias com Kelly',
    'team_title': 'Kelly Farias à frente da Komuniki',
    'team_description': 'Jornalista, atriz, radialista, diretora de produção executiva, editora-chefe, mentora e professora de comunicação.',
    'testimonials_eyebrow': 'Alunos',
    'testimonials_title': 'Trajetórias em comunicação e artes',
    'testimonials_description': 'Depoimentos reais podem ser destacados no admin quando a Komuniki quiser publicar relatos de alunos e participantes.',
    'hiring_title': 'Cursos e mentorias',
    'hiring_description': 'Conheça formações para comunicação, artes, apresentação, produção, locução, assessoria e desenvolvimento de estilo de comunicação.',
    'contact_title': 'Conte-nos mais',
    'contact_description': 'Fale com a Komuniki para tirar dúvidas, consultar turmas, solicitar mentorias ou conversar sobre projetos corporativos e culturais.',
    'meta_title': 'Komuniki - Comunicação que gera resultados',
    'meta_description': 'Cursos e mentorias em comunicação, artes e liderança com Kelly Farias.',
    'meta_keywords': 'komuniki, kelly farias, comunicação, artes, liderança, cursos, mentorias',
}


HOME_CONTENT_EN = {
    'hero_badge': 'School of communication, arts and leadership',
    'hero_title': 'Communication that drives results',
    'hero_subtitle': 'Mentoring and courses for people who want to express themselves better, work in audiovisual media, build art-driven ventures and communicate with clarity.',
    'visual_eyebrow': 'Komuniki',
    'visual_title': 'Education for communication and the arts',
    'visual_footer_title': 'Courses, mentoring and projects with real-world application',
    'visual_footer_text': 'Komuniki combines technical training, market practice and close guidance for individuals, artists, communicators and corporate teams.',
    'proposal_eyebrow': 'What we do',
    'proposal_title': 'Courses for communication, culture and professional presence',
    'proposal_description': 'Created by Kelly Farias, Komuniki offers professional training, open courses and mentoring in communication, culture, stage presence, writing and self-confidence.',
    'life_eyebrow': 'Projects and impact',
    'life_title': 'Communication, culture and protagonism',
    'life_description': 'Komuniki also runs Jovem Comunicador, a social project for young people in vulnerable situations, and creates connections between training, art and the market.',
    'team_eyebrow': 'Mentoring with Kelly',
    'team_title': 'Kelly Farias leading Komuniki',
    'team_description': 'Journalist, actress, radio host, executive production director, editor-in-chief, mentor and communication teacher.',
    'testimonials_eyebrow': 'Students',
    'testimonials_title': 'Journeys in communication and the arts',
    'testimonials_description': 'Real testimonials can be highlighted in the admin whenever Komuniki wants to publish stories from students and participants.',
    'hiring_title': 'Courses and mentoring',
    'hiring_description': 'Explore training in communication, arts, presenting, production, voice work, press relations and communication style development.',
    'contact_title': 'Tell us more',
    'contact_description': 'Talk to Komuniki to ask questions, check classes, request mentoring or discuss corporate and cultural projects.',
    'meta_title': 'Komuniki - Communication that drives results',
    'meta_description': 'Courses and mentoring in communication, arts and leadership with Kelly Farias.',
    'meta_keywords': 'komuniki, kelly farias, communication, arts, leadership, courses, mentoring',
}


FEATURE_CONTENT = [
    ('trust', 'Mentorias com Kelly Farias', 'Acompanhamento para desenvolver presença, estilo de comunicação e clareza na expressão.', 'Mentoring with Kelly Farias', 'Guidance to develop presence, communication style and clarity of expression.'),
    ('trust', 'Cursos online, híbridos e presenciais', 'Formações flexíveis para comunicação, artes, liderança e produção.', 'Online, hybrid and in-person courses', 'Flexible training in communication, arts, leadership and production.'),
    ('trust', 'Atuação corporativa', 'Mentorias, palestras e comunicação interna para equipes e projetos.', 'Corporate work', 'Mentoring, talks and internal communication for teams and projects.'),
    ('trust', 'Projeto Jovem Comunicador', 'Iniciativa social voltada a jovens em situação de vulnerabilidade social.', 'Jovem Comunicador project', 'A social initiative for young people in vulnerable situations.'),
    ('proposal', 'Comunicador Profissionalizante', 'Formação de 350 horas em 18 meses, com encaminhamento para registro profissional de Comunicador.', 'Professional Communicator', 'A 350-hour, 18-month program with guidance toward professional Communicator registration.'),
    ('proposal', 'Produção Cultural', 'Formação de 250 horas em 12 meses, com encaminhamento para registro profissional Diretor de produção.', 'Cultural Production', 'A 250-hour, 12-month program with guidance toward professional Production Director registration.'),
    ('proposal', 'Jornalismo Cultural', 'Curso livre de 30 horas para jornalistas, influenciadores e produtores de conteúdo.', 'Cultural Journalism', 'A 30-hour open course for journalists, influencers and content producers.'),
    ('proposal', 'Apresentação de Palco e Eventos', 'Curso livre de 50 horas com técnicas de apresentação e condução de eventos.', 'Stage and Event Presenting', 'A 50-hour open course with presenting and event-hosting techniques.'),
    ('proposal', 'Espanhol – Conversação e Escrita', 'Curso livre para desenvolvimento da comunicação oral e escrita.', 'Spanish - Conversation and Writing', 'An open course to develop oral and written communication.'),
    ('proposal', 'Comunicação Destravada', '20 horas em curso coletivo ou mentoria individual para oratória, comunicação e autoconfiança.', 'Unlocked Communication', '20 hours in a group course or individual mentoring for public speaking, communication and self-confidence.'),
    ('life', 'Comunicador Profissionalizante', 'Formação de 350 horas, com encaminhamento para registro profissional de Comunicador.', 'Professional Communicator', 'A 350-hour program with guidance toward professional Communicator registration.'),
    ('life', 'Arte e empreendedorismo', 'Formações como Artista Empreendedor, Estilo de Comunicação e Conexão.', 'Art and entrepreneurship', 'Training such as Entrepreneur Artist, Communication Style and Connection.'),
    ('life', 'Eventos e palestras', 'Encontros, fórum de protagonismo juvenil e experiências formativas ao vivo.', 'Events and talks', 'Meetups, a youth protagonism forum and live training experiences.'),
    ('life', 'Certificação e registro profissional', 'Cursos com certificação e consulta de disponibilidade para autorização via sindicatos.', 'Certification and professional registration', 'Courses with certification and availability checks for authorization through unions.'),
]


def populate_english_content(apps, schema_editor):
    SchoolHomeConfig = apps.get_model('school', 'SchoolHomeConfig')
    SchoolFeature = apps.get_model('school', 'SchoolFeature')

    for home_config in SchoolHomeConfig.objects.all():
        update_fields = []
        for field, pt_value in HOME_CONTENT_PT.items():
            en_field = f'{field}_en'
            if getattr(home_config, en_field):
                continue
            if getattr(home_config, field) != pt_value:
                continue
            setattr(home_config, en_field, HOME_CONTENT_EN[field])
            update_fields.append(en_field)
        if update_fields:
            home_config.save(update_fields=update_fields)

    for placement, title, description, title_en, description_en in FEATURE_CONTENT:
        features = SchoolFeature.objects.filter(placement=placement, title=title)
        for feature in features:
            update_fields = []
            if not feature.title_en:
                feature.title_en = title_en
                update_fields.append('title_en')
            if not feature.description_en and feature.description == description:
                feature.description_en = description_en
                update_fields.append('description_en')
            if update_fields:
                feature.save(update_fields=update_fields)


def noop_reverse(apps, schema_editor):
    # Conteúdo traduzido pode ter sido editado depois da migração; não removemos no rollback.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_komuniki_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolfeature',
            name='description_en',
            field=models.TextField(blank=True, default='', help_text='Opcional. Se vazio, usa a descrição em português.', verbose_name='Descrição (EN)'),
        ),
        migrations.AddField(
            model_name='schoolfeature',
            name='title_en',
            field=models.CharField(blank=True, default='', help_text='Opcional. Se vazio, usa o título em português.', max_length=160, verbose_name='Título (EN)'),
        ),
        migrations.AddField(
            model_name='schoolhomeconfig',
            name='contact_description_en',
            field=models.TextField(blank=True, default='', help_text='Opcional. Se vazio, usa o texto em português.', verbose_name='Descrição de contato (EN)'),
        ),
        migrations.AddField(
            model_name='schoolhomeconfig',
            name='contact_title_en',
            field=models.CharField(blank=True, default='', help_text='Opcional. Se vazio, usa o texto em português.', max_length=200, verbose_name='Título de contato (EN)'),
        ),
        migrations.AddField(
            model_name='schoolhomeconfig',
            name='hero_badge_en',
            field=models.CharField(blank=True, default='', help_text='Opcional. Se vazio, usa o texto em português.', max_length=120, verbose_name='Selo do hero (EN)'),
        ),
        migrations.AddField(
            model_name='schoolhomeconfig',
            name='hero_subtitle_en',
            field=models.TextField(blank=True, default='', help_text='Opcional. Se vazio, usa o texto em português.', verbose_name='Subtítulo do hero (EN)'),
        ),
        migrations.AddField(
            model_name='schoolhomeconfig',
            name='hero_title_en',
            field=models.CharField(blank=True, default='', help_text='Opcional. Se vazio, usa o texto em português.', max_length=200, verbose_name='Título do hero (EN)'),
        ),
        migrations.AddField(
            model_name='schoolhomeconfig',
            name='hiring_description_en',
            field=models.TextField(blank=True, default='', help_text='Opcional. Se vazio, usa o texto em português.', verbose_name='Descrição de trabalhe conosco (EN)'),
        ),
        migrations.AddField(
            model_name='schoolhomeconfig',
            name='hiring_title_en',
            field=models.CharField(blank=True, default='', help_text='Opcional. Se vazio, usa o texto em português.', max_length=200, verbose_name='Título de trabalhe conosco (EN)'),
        ),
        migrations.AddField(
            model_name='schoolhomeconfig',
            name='life_description_en',
            field=models.TextField(blank=True, default='', help_text='Opcional. Se vazio, usa o texto em português.', verbose_name='Descrição de vida escolar (EN)'),
        ),
        migrations.AddField(
            model_name='schoolhomeconfig',
            name='life_eyebrow_en',
            field=models.CharField(blank=True, default='', help_text='Opcional. Se vazio, usa o texto em português.', max_length=120, verbose_name='Chamada de vida escolar (EN)'),
        ),
        migrations.AddField(
            model_name='schoolhomeconfig',
            name='life_title_en',
            field=models.CharField(blank=True, default='', help_text='Opcional. Se vazio, usa o texto em português.', max_length=200, verbose_name='Título de vida escolar (EN)'),
        ),
        migrations.AddField(
            model_name='schoolhomeconfig',
            name='meta_description_en',
            field=models.CharField(blank=True, default='', help_text='Opcional. Se vazio, usa a descrição SEO em português.', max_length=160, verbose_name='Descrição SEO (EN)'),
        ),
        migrations.AddField(
            model_name='schoolhomeconfig',
            name='meta_keywords_en',
            field=models.CharField(blank=True, default='', help_text='Opcional. Se vazio, usa as palavras-chave SEO em português.', max_length=255, verbose_name='Palavras-chave SEO (EN)'),
        ),
        migrations.AddField(
            model_name='schoolhomeconfig',
            name='meta_title_en',
            field=models.CharField(blank=True, default='', help_text='Opcional. Se vazio, usa o título SEO em português.', max_length=70, verbose_name='Título SEO (EN)'),
        ),
        migrations.AddField(
            model_name='schoolhomeconfig',
            name='proposal_description_en',
            field=models.TextField(blank=True, default='', help_text='Opcional. Se vazio, usa o texto em português.', verbose_name='Descrição da proposta (EN)'),
        ),
        migrations.AddField(
            model_name='schoolhomeconfig',
            name='proposal_eyebrow_en',
            field=models.CharField(blank=True, default='', help_text='Opcional. Se vazio, usa o texto em português.', max_length=120, verbose_name='Chamada da proposta (EN)'),
        ),
        migrations.AddField(
            model_name='schoolhomeconfig',
            name='proposal_title_en',
            field=models.CharField(blank=True, default='', help_text='Opcional. Se vazio, usa o texto em português.', max_length=200, verbose_name='Título da proposta (EN)'),
        ),
        migrations.AddField(
            model_name='schoolhomeconfig',
            name='team_description_en',
            field=models.TextField(blank=True, default='', help_text='Opcional. Se vazio, usa o texto em português.', verbose_name='Descrição da equipe (EN)'),
        ),
        migrations.AddField(
            model_name='schoolhomeconfig',
            name='team_eyebrow_en',
            field=models.CharField(blank=True, default='', help_text='Opcional. Se vazio, usa o texto em português.', max_length=120, verbose_name='Chamada da equipe (EN)'),
        ),
        migrations.AddField(
            model_name='schoolhomeconfig',
            name='team_title_en',
            field=models.CharField(blank=True, default='', help_text='Opcional. Se vazio, usa o texto em português.', max_length=200, verbose_name='Título da equipe (EN)'),
        ),
        migrations.AddField(
            model_name='schoolhomeconfig',
            name='testimonials_description_en',
            field=models.TextField(blank=True, default='', help_text='Opcional. Se vazio, usa o texto em português.', verbose_name='Descrição de depoimentos (EN)'),
        ),
        migrations.AddField(
            model_name='schoolhomeconfig',
            name='testimonials_eyebrow_en',
            field=models.CharField(blank=True, default='', help_text='Opcional. Se vazio, usa o texto em português.', max_length=120, verbose_name='Chamada de depoimentos (EN)'),
        ),
        migrations.AddField(
            model_name='schoolhomeconfig',
            name='testimonials_title_en',
            field=models.CharField(blank=True, default='', help_text='Opcional. Se vazio, usa o texto em português.', max_length=200, verbose_name='Título de depoimentos (EN)'),
        ),
        migrations.AddField(
            model_name='schoolhomeconfig',
            name='visual_eyebrow_en',
            field=models.CharField(blank=True, default='', help_text='Opcional. Se vazio, usa o texto em português.', max_length=120, verbose_name='Chamada visual (EN)'),
        ),
        migrations.AddField(
            model_name='schoolhomeconfig',
            name='visual_footer_text_en',
            field=models.TextField(blank=True, default='', help_text='Opcional. Se vazio, usa o texto em português.', verbose_name='Texto do bloco de comunidade (EN)'),
        ),
        migrations.AddField(
            model_name='schoolhomeconfig',
            name='visual_footer_title_en',
            field=models.CharField(blank=True, default='', help_text='Opcional. Se vazio, usa o texto em português.', max_length=200, verbose_name='Título do bloco de comunidade (EN)'),
        ),
        migrations.AddField(
            model_name='schoolhomeconfig',
            name='visual_title_en',
            field=models.CharField(blank=True, default='', help_text='Opcional. Se vazio, usa o texto em português.', max_length=200, verbose_name='Título do bloco visual (EN)'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='quote_en',
            field=models.TextField(blank=True, default='', help_text='Opcional. Se vazio, usa o depoimento em português.', verbose_name='Depoimento (EN)'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='relationship_en',
            field=models.CharField(blank=True, default='', help_text='Opcional. Se vazio, usa a relação em português.', max_length=200, verbose_name='Relação com a escola (EN)'),
        ),
        migrations.RunPython(populate_english_content, noop_reverse),
    ]
