# Generated by Codex on 2026-06-02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediafile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Arquivo de Mídia', 'verbose_name_plural': 'Arquivos de Mídia'},
        ),
        migrations.AlterModelOptions(
            name='mediafolder',
            options={'ordering': ['name'], 'verbose_name': 'Pasta de Mídia', 'verbose_name_plural': 'Pastas de Mídia'},
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Descreva imagens para acessibilidade. Ex.: alunos em laboratório de ciências.', max_length=255, verbose_name='Texto alternativo'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=models.FileField(upload_to='media_library/files/', verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='file_size',
            field=models.PositiveIntegerField(default=0, help_text='Tamanho em bytes.', verbose_name='Tamanho do arquivo'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='file_type',
            field=models.CharField(choices=[('image', 'Imagem'), ('document', 'Documento'), ('video', 'Vídeo'), ('audio', 'Áudio'), ('other', 'Outro')], default='other', max_length=20, verbose_name='Tipo de arquivo'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='media_library.mediafolder', verbose_name='Pasta'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Enviado por'),
        ),
        migrations.AlterField(
            model_name='mediafolder',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='mediafolder',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Use apenas quando esta pasta deve ficar dentro de outra.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='media_library.mediafolder', verbose_name='Pasta superior'),
        ),
    ]
