# Generated by Django 5.2.17 on 2026-09-25 12:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_library", "0003_timestamp_labels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediafile",
            name="file",
            field=models.FileField(
                help_text="Imagens (JPG, PNG, WebP, GIF, BMP), documentos (PDF, Office, texto), vídeo ou áudio.",
                upload_to="media_library/files/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        [
                            "aac",
                            "avi",
                            "bmp",
                            "csv",
                            "doc",
                            "docx",
                            "flac",
                            "gif",
                            "jpeg",
                            "jpg",
                            "m4a",
                            "mkv",
                            "mov",
                            "mp3",
                            "mp4",
                            "odt",
                            "ogg",
                            "pdf",
                            "png",
                            "ppt",
                            "pptx",
                            "rtf",
                            "txt",
                            "wav",
                            "webm",
                            "webp",
                            "xls",
                            "xlsx",
                        ]
                    )
                ],
                verbose_name="Arquivo",
            ),
        ),
    ]
