# Generated by Django 5.2.12 on 2026-06-10 16:24

import apps.common.validators
import apps.social.models
import django.contrib.sites.managers
import django.db.models.deletion
import django.db.models.manager
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('tiktok', 'TikTok')], max_length=20, verbose_name='Plataforma')),
                ('display_name', models.CharField(help_text='Nome amigável usado no admin. Ex: Komuniki no Instagram.', max_length=120, verbose_name='Nome de exibição')),
                ('username', models.CharField(blank=True, help_text='Nome de usuário público, sem o @. Ex: komunikiescola.', max_length=120, verbose_name='Usuário (@)')),
                ('profile_url', models.URLField(blank=True, help_text='Endereço público do perfil. Ex: https://www.instagram.com/komunikiescola/', verbose_name='Link do perfil')),
                ('external_user_id', models.CharField(blank=True, help_text='Preenchido ao conectar a API oficial. Pode ficar em branco no uso manual.', max_length=120, verbose_name='ID da conta na API')),
                ('access_token', models.TextField(blank=True, help_text='Sensível. Usado apenas para conectar a API oficial. Prefira variável de ambiente; nunca compartilhe nem versione.', verbose_name='Token de acesso')),
                ('refresh_token', models.TextField(blank=True, help_text='Sensível. Opcional, usado por algumas APIs para renovar o acesso.', verbose_name='Token de atualização')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Token expira em')),
                ('is_active', models.BooleanField(default=True, help_text='Apenas contas ativas aparecem no site e são sincronizadas.', verbose_name='Ativa')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Última sincronização')),
                ('last_sync_status', models.CharField(choices=[('never', 'Nunca sincronizado'), ('success', 'Sucesso'), ('failed', 'Falha'), ('partial', 'Parcial')], default='never', max_length=20, verbose_name='Status da última sincronização')),
                ('last_sync_error', models.TextField(blank=True, verbose_name='Erro da última sincronização')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to='sites.site', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Conta de Rede Social',
                'verbose_name_plural': 'Contas de Redes Sociais',
                'ordering': ['platform', 'display_name'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('tiktok', 'TikTok')], db_index=True, max_length=20, verbose_name='Plataforma')),
                ('external_id', models.CharField(blank=True, help_text='ID do post na API. Em posts manuais é gerado automaticamente.', max_length=255, verbose_name='ID do post na plataforma')),
                ('permalink', models.URLField(help_text='Endereço da publicação original. Ex: https://www.instagram.com/p/XXXX/', max_length=500, verbose_name='Link público do post')),
                ('caption', models.TextField(blank=True, verbose_name='Legenda')),
                ('media_type', models.CharField(choices=[('image', 'Imagem'), ('video', 'Vídeo'), ('carousel', 'Carrossel'), ('reel', 'Reel'), ('unknown', 'Desconhecido')], default='unknown', max_length=20, verbose_name='Tipo de mídia')),
                ('thumbnail_url', models.URLField(blank=True, help_text='Usada pela sincronização automática. Pode ficar em branco e enviar uma imagem abaixo.', max_length=500, verbose_name='URL da miniatura')),
                ('media_url', models.URLField(blank=True, help_text='Link direto da imagem/vídeo na plataforma (opcional).', max_length=500, verbose_name='URL da mídia')),
                ('thumbnail_image', imagekit.models.fields.ProcessedImageField(blank=True, help_text='Opcional. Para posts manuais: envie uma imagem (otimizada automaticamente). Tem prioridade sobre a URL da miniatura.', upload_to=apps.social.models.social_thumbnail_upload_path, validators=[apps.common.validators.validate_uploaded_image], verbose_name='Imagem da miniatura (upload)')),
                ('published_at', models.DateTimeField(db_index=True, verbose_name='Publicado em')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visível no site')),
                ('is_manual', models.BooleanField(default=True, help_text='Desmarcado automaticamente quando o post vem da sincronização da API.', verbose_name='Cadastrado manualmente')),
                ('sync_payload', models.JSONField(blank=True, default=dict, help_text='Resumo técnico do retorno da API. Não contém tokens.', verbose_name='Payload da sincronização')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='social.socialaccount', verbose_name='Conta')),
            ],
            options={
                'verbose_name': 'Post de Rede Social',
                'verbose_name_plural': 'Posts de Redes Sociais',
                'ordering': ['-published_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='socialaccount',
            constraint=models.UniqueConstraint(fields=('site', 'platform', 'username'), name='unique_social_account_per_site_platform_username'),
        ),
        migrations.AddIndex(
            model_name='socialpost',
            index=models.Index(fields=['platform'], name='social_soci_platfor_1de333_idx'),
        ),
        migrations.AddIndex(
            model_name='socialpost',
            index=models.Index(fields=['published_at'], name='social_soci_publish_4ce291_idx'),
        ),
        migrations.AddIndex(
            model_name='socialpost',
            index=models.Index(fields=['is_visible'], name='social_soci_is_visi_e4f20c_idx'),
        ),
        migrations.AddConstraint(
            model_name='socialpost',
            constraint=models.UniqueConstraint(fields=('platform', 'external_id'), name='unique_social_post_platform_external_id'),
        ),
    ]
